### ISSUE TITLE
plugins should not require gulp as a dependency

### ISSUE THREAD

**Issue by stevelacy** [futurechan/gulp-asset-transform#16]
gulp plugins should not require gulp as a dependency.
https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md

**Comment by futurechan** [comment]
@stevelacy this plugin doesn't actually rely on gulp. There was a stray reference. I am removing it and bumping the version. Thanks for the heads up.

**Comment by futurechan** [comment]
@stevelacy ok, it does rely on gulp for the glob stream. I'm fixing this. Thanks again.

**Comment by futurechan** [comment]
@stevelacy I've published as 1.6.3. I'm closing this. Let me know if you need anything else. Thanks.
