### ISSUE TITLE
Ability to change file.base (alternate search path)

### ISSUE THREAD

**Issue by unlight** [futurechan/gulp-asset-transform#19]
In usemin we can set search path
```html
<!-- build:<pipelineId>(alternate search path) <path> -->
```
I did not find such ability for `gulp-asset-transform`

**Comment by unlight** [comment]
Sorry. did not spot https://github.com/futurechan/gulp-asset-transform/issues/10
Is it the same issue?

**Comment by futurechan** [comment]
Yes, it does. I haven't had a lot of time to work on this lately. I'll gladly review and accept PRs. If you would like to use this repo, but this one issue is a roadblock, and you can't make the code change yourself, I will try to do this asap.
