### ISSUE TITLE
Create stream for concat instead of using a string

### ISSUE THREAD

**Issue by futurechan** [futurechan/gulp-asset-transform#3]
By using the stream function strategy, this is already supported. However, we should deprecate the magic ```'concat'``` string in favor of a special concat object for the tasks array strategy.

**Comment by danilo-valente** [comment]
I've implemented that `at.concat` method. Please check it [here](https://github.com/danilo-valente/gulp-asset-transform/tree/concat_stream). If that's what you meant, I'll open a PR.

**Comment by futurechan** [comment]
Looks good.
